apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: dstrategies-back
  name: dstrategies-back-online
spec:
  to:
    kind: Service
    name: dstrategies-back-online
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect