apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dstrategies-back-vs
spec:
  gateways:
  - dborrego-gw
  hosts:
  - dstrategies-back-online-dborrego.apps.cluster-5tgc2.5tgc2.sandbox2406.opentlc.com
  http:
  - name: primary
    route:
    - destination:
        host: dstrategies-back-online
      weight: 100
    - destination:
        host: dstrategies-back-offline
      weight: 0