apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-canary
  namespace: ${USER}-gitops-argocd
spec:
  destination:
    namespace: ${USER}-canary
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: global.namespace
          value: ${USER}-canary
      valueFiles:
        - values/values-canary-rollouts.yaml
    path: helm/quarkus-helm-umbrella/chart
    repoURL: 'https://github.com/davidseve/cloud-native-deployment-strategies.git'
    targetRevision: rollouts2
  syncPolicy:
    automated: {}