apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-blue-green
  namespace: ${USER}-gitops-argocd
spec:
  destination:
    namespace: ${USER}-blue-green
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: global.namespace
          value: ${USER}-blue-green
      valueFiles:
        - values/values-rollouts.yaml
    path: helm/quarkus-helm-umbrella/chart
    repoURL: 'https://github.com/davidseve/cloud-native-deployment-strategies.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}