apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: web-terminal-exec
  namespace: openshift-operators
spec:
  components:
    - container:
        cpuRequest: 100m
        command:
          - /go/bin/che-machine-exec
          - '--authenticated-user-id'
          - $(DEVWORKSPACE_CREATOR)
          - '--idle-timeout'
          - $(WEB_TERMINAL_IDLE_TIMEOUT)
          - '--pod-selector'
          - controller.devfile.io/devworkspace_id=$(DEVWORKSPACE_ID)
          - '--use-tls'
          - '--use-bearer-token'
        env:
          - name: WEB_TERMINAL_IDLE_TIMEOUT
            value: 15m
        memoryRequest: 128Mi
        sourceMapping: /projects
        cpuLimit: 400m
        memoryLimit: 128Mi
        image: >-
          registry.redhat.io/web-terminal/web-terminal-exec-rhel8@sha256:c82e89d9e8a5d1c9e5c94835d38cb601e5e1ecb1e53cb038d0423b1b19d98683
        endpoints:
          - attributes:
              type: main
            exposure: public
            name: exec
            protocol: http
            targetPort: 4444
        mountSources: false
      name: web-terminal-exec
