apiVersion: v1
kind: ConfigMap
metadata:
  name: "dstrategies-back-configmap-env-base"
  labels:
    app.kubernetes.io/name: dstrategies-back
    app: dstrategies-back
    version: "0.2"
data:
  application.version: latest
  quarkus.log.level: DEBUG
  quarkus.jaeger.service-name: "dstrategies-back"
  quarkus.jaeger.sampler-type: "const"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.endpoint: "http://jaeger-collector.gitops.svc:14268/api/traces"
  quarkus.jaeger.propagation: "b3"
  quarkus.jaeger.reporter-log-spans: "true"
