kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ include "service.name" . }}
spec:
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts: 
        - {{ include "service.name" . }}-{{ .Release.Namespace }}.apps.{{ .Values.dns }}
  selector:
    istio: ingressgateway