apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "service.name" . }}-dborrego
  namespace: istio-system
spec:
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect