apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "service.name" . }}
spec:
  gateways:
  - {{ include "service.name" . }}
  hosts:
  - dstrategies-back-dborrego-istio-system.apps.acidonpe19.sandbox2617.opentlc.com
  http:
  - name: primary
    route:
    - destination:
        host: {{ include "service.name" . }}
        subset: stable
      weight: 100
    - destination:
        host: {{ include "service.name" . }}
        subset: canary
      weight: 0