apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "service.name" . }}
spec:
  gateways:
  - {{ include "service.name" . }}
  hosts:
  - {{ include "service.name" . }}-{{ .Release.Namespace }}.apps.cluster-5tgc2.5tgc2.sandbox2406.opentlc.com
  http:
  - name: primary
    route:
    - destination:
        host: {{ include "service.name" . | quote}}
        subset: stable
      weight: 100
    - destination:
        host: {{ include "service.name" . | quote }}
        subset: canary
      weight: 0